### PR TITLE
Add the m2_simulation_analysis.ipynb.

### PR DESCRIPTION
**Pull request by teweitsai**
Add the m2_simulation_analysis.ipynb.

### CODE REVIEW

**Comment by teweitsai** [comment]
<p>This depends. Bo had the request before that the user should be able to change the mode by SAL.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>No</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>They will be calculated/assigned below in blocks.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>They are read/calculated from the configuration files.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>The linear fitting is used.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>I only know the weight of surrogate should be close to mirror.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>Yes from the AOS.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
<p>This is to evaluate all the possible condition.</p>

---

 <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/98/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by teweitsai** [comment]
Went through all the details with Pablo. There should be no doubt now. Clear all the outputs.

**Review by pzorzi — APPROVED** [review]
The code looks clear and right. All the questions that I asked the code owner were properly answered by him. I approve the code as it is.

**Pull request merged**
