### PR TITLE
Tickets/dm 29548

### PR DESCRIPTION
**Pull request by bxin**
My latest MTAOS Notebooks, for 

LVV-T2190 MTAOS add aberrations to M1M3+M2+Hexapods
- AddAberration.ipynb

LVV-T2241 MTAOS correction accumulation
- aosCmdAccum.ipynb

LVV-T2193 MTAOS handling of rejected commands 
- aosCmdReject.ipynb
- this has not been fully tested.
- `cmd_rejectCorrection` should publish new DOF and Correction events. Tiago fixed it on a branch. Not sure if this has been updated on the NTS. I did not get a chance to test it.

Again, these are in my personal area. So I think it would be useful to be able to merge in the next couple of days. Otherwise these may get lost forever...

### CODE REVIEW

**Comment by sandrinethomas** [comment]
This is very handy, and we have been using some of these notebook already from Bo's area.
A couple of comments: 
- If would be very useful to get some notes in aosTools.py
- The difference between aos2comp. py  and aosCmdAccum seem very close togeter. Any reasons we need both?

**Comment by tribeiro** [comment]
Note that most of the things in aosTools are migrating to more permanent places. Mostly to ts_observatory_control.

**Comment by bxin** [comment]
Thanks @tribeiro for agreeing to reformat the code in aosTools and add in docstrings.
To answer Sandrine's other question - a lot of cells are in common between aos2comp.ipynb and aosCmdAccum.ipynb, because they need to set up the same components. The difference is that one simply tests the communication between MTAOS and the AOS components by using the `cmd_addAberration` once, and the other does it twice to check the OFC does the accounting on the DOFs and corrections properly. See the test scripts in the Jira test cases for more details.

**Review by sandrinethomas — APPROVED** [review]
I happy with the responses Bo provided.

**Pull request merged**
