### PR TITLE
demostrate how M2 FB system works

### PR DESCRIPTION
**Pull request by bxin**

### CODE REVIEW

**Review by teweitsai — APPROVED** [review]
I do not want to block this PR. If you could put the output in the `ts_notebooks/bxin/ptg2m2/m2_diagnostic_EFD.ipynb`, that should be great! Thanks!

**Comment by bxin** [comment]
I think it is the policy of this repo to clear output before committing notebooks.

**Comment by teweitsai** [comment]
Sure. In this case, can you help to give me the link to use the summit EFD? I only have the link to use the chronograph. Let me see I can run your notebook to get the result or not. I have the plan to document the formula you used into the confluence page and compare with the implemented M2 cell code (hope I could figure out the Harris's code). Thanks!

**Comment by bxin** [comment]
If you use the efdClient, I don't think you need any additional link or setting to access the summit EFD.
An alternative is that I can commit a version with output, just for reviewing purposes. I can clear the outputs again before merging. Let me know.

**Comment by teweitsai** [comment]
I tried to reproduce this notebook in `https://base-lsp.lsst.codes` and got the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/teweitsai/notebooks/M2_summit_2003/harrisLUT/FinalHandlingLUTs/F_E.csv'
```

Can you help to put the needed data in `ts_notebooks` and update the file path in the notebook? Thanks!

**Comment by teweitsai** [comment]
OK. I copied all files as the followings:
Screen Shot 2021-02-21 at 11 19 46 AM

And I could reproduce the calculation:
Screen Shot 2021-02-21 at 11 21 41 AM

Thanks!

**Pull request merged**
