### PR TITLE
New notebook for verifying image ingestion at the summit and at NCSA

### PR DESCRIPTION
**Pull request by b1quint**
A new notebook that uses butler to query a data set to check if it was properly ingested at the Summit and at NCSA. It prints out the metadata using two different methods.

### CODE REVIEW

**Review by Slimleashma — COMMENTED** [review]
Just out of curiosity, does the detector need to be specified each time? What other metadata other than detector number will be dependent on the detector?

**Review by edennihy — APPROVED** [review]
Should be good enough for what we need now. Might want to add a comment about what to do if the image get fails though? Or add a comment on what are some basic metadata values to check?

**Comment by b1quint** [comment]
I am not sure what would be the procedure for when the image ingestion fails. I suspect that would require a ticket or sending a message to the #com-square-support Slack channel. Maybe @tribeiro knows?

**Comment by b1quint** [comment]
Regarding @Slimleashma 's question: I tried it out here and Butler raises an error if we do not provide the detector. So we always need to pass this keyword. Regarding your second question about what other metadata would be dependant on the detector, I don't know the answer yet either.

**Comment by tribeiro** [comment]
> I am not sure what would be the procedure for when the image ingestion fails. I suspect that would require a ticket or sending a message to the #com-square-support Slack channel. Maybe @tribeiro knows?

I don't think #com-square-support would be the right channel, as that is mostly for "square" not DM/Camera in general. 

For comcam failures in general we should probably @ Tony Johnson (tonyj) and Stephen Pietrowicz (srp) in #comcam-work-log....

**Pull request merged**
