### PR TITLE
Create a notebook to run LVV-T2228 and LVV-T2229

### PR DESCRIPTION
**Pull request by b1quint**
Creates a new notebook to follow the Test Script [LVV-T2229](https://jira.lsstcorp.org/secure/Tests.jspa#/testCase/LVV-T2229).

### CODE REVIEW

**Comment by b1quint** [comment]
LVV-T2228 runs slew, track, take images intra/at/extra-focus for one target. The notebook was updated to reflect that.

LVV-T2229 runs the same but for two targets. The second target is still pending but we might want to merge this to develop to avoid having to switch branches between tests.

LVV-T2229_v1 and LVV-T2229_v2 are basically the same and were kept just for keeping track. LVV-T2229_v2 is more structured but I believe that all the steps are the same. Maybe we want to keep only v2?

**Comment by b1quint** [comment]
After reading the comment above I realized that it did not make sense to have LVV-2229_v1 and LVV-2229_v2.

**Comment by tribeiro** [comment]
I made a few comments on the LVV-T2228 notebook. When reviewing LVV-T2229 notebook I saw it explicitly says it is a version 2.0 of LVV-T2228, but actually, although they are similar, LVV-2229 is rather different. My suggestion would be to edit LVV-2229 to remove any reference of it being version 2 of LVV-2228. Instead, I think it would be ok to reference LVV-2228 as a precursor of LVV-2229 but make it clear that this one has a different purpose. I imagine they can co-exist for some time and that 29 will end up replacing 28, but 28 may be kept in the back burner for some smaller scale testing. 

Also, I think the comments I made to LVV-T2228 are relevant to 2229.

**Comment by b1quint** [comment]
Did a final force push since I rebased `develop` into this branch. I hope I did not mess up with anything. All the requested changes should be applied to both notebooks.

**Review by tribeiro — APPROVED** [review]
Looks good! thanks for the updates!

**Comment by b1quint** [comment]
Thank you! Merging now!

**Pull request merged**
